CREATE TABLE CART
(M_ID VARCHAR2(100),
b_store varchar2(100),
p_name varchar2(100),
P_NUM NUMBER,
p_oriprice NUMBER,
p_price NUMBER,
P_SIZE VARCHAR2(100),
C_QUANTITY NUMBER);


CREATE TABLE ORDERS
(M_ID VARCHAR2(100),
O_NUM NUMBER,
O_ADDR1 VARCHAR2(100),
O_ADDR2 VARCHAR2(100),
O_ADDR3 VARCHAR2(100),
O_TEL VARCHAR2(100),
O_DATE DATE,
O_MEMO VARCHAR2(100),
O_STATE VARCHAR2(100),
O_PAYTYPE VARCHAR2(100),
O_NAME VARCHAR2(100),
O_POINT NUMBER,
C_NUM NUMBER,
C_DIS NUMBER,
O_TOTAL NUMBER,
O_PRICE NUMBER,
CONSTRAINT PK_ORDERS_NUM PRIMARY KEY(O_NUM),
CONSTRAINT FK_ORDERS_ID FOREIGN KEY(M_ID) REFERENCES MEM(M_ID));
